// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package org.example.stubs;

public final class Bank {
  private Bank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\"S\n\006Client\022\n\n\002id\030\001 \001(\t\022\013\n\003no" +
      "m\030\002 \001(\t\022\016\n\006prenom\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\021" +
      "\n\ttelephone\030\005 \001(\t\"E\n\007Chambre\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004type\030\002 \001(\t\022\014\n\004prix\030\003 \001(\002\022\022\n\ndisponib" +
      "le\030\004 \001(\010\"\206\001\n\013Reservation\022\n\n\002id\030\001 \001(\t\022\027\n\006" +
      "client\030\002 \001(\0132\007.Client\022\031\n\007chambre\030\003 \001(\0132\010" +
      ".Chambre\022\021\n\tdateDebut\030\004 \001(\t\022\017\n\007dateFin\030\005" +
      " \001(\t\022\023\n\013preferences\030\006 \001(\t\"r\n\022Reservation" +
      "Request\022\020\n\010clientId\030\001 \001(\t\022\021\n\tchambreId\030\002" +
      " \001(\t\022\021\n\tdateDebut\030\003 \001(\t\022\017\n\007dateFin\030\004 \001(\t" +
      "\022\023\n\013preferences\030\005 \001(\t\"8\n\023ReservationResp" +
      "onse\022!\n\013reservation\030\001 \001(\0132\014.Reservation\"" +
      "\'\n\031GetReservationByIdRequest\022\n\n\002id\030\001 \001(\t" +
      "\"?\n\032GetReservationByIdResponse\022!\n\013reserv" +
      "ation\030\001 \001(\0132\014.Reservation\"\033\n\031GetAllReser" +
      "vationsRequest\"@\n\032GetAllReservationsResp" +
      "onse\022\"\n\014reservations\030\001 \003(\0132\014.Reservation" +
      "\"\204\001\n\030UpdateReservationRequest\022\n\n\002id\030\001 \001(" +
      "\t\022\020\n\010clientId\030\002 \001(\t\022\021\n\tchambreId\030\003 \001(\t\022\021" +
      "\n\tdateDebut\030\004 \001(\t\022\017\n\007dateFin\030\005 \001(\t\022\023\n\013pr" +
      "eferences\030\006 \001(\t\"&\n\030DeleteReservationRequ" +
      "est\022\n\n\002id\030\001 \001(\t\",\n\031DeleteReservationResp" +
      "onse\022\017\n\007success\030\001 \001(\0102\204\003\n\022ReservationSer" +
      "vice\022>\n\021createReservation\022\023.ReservationR" +
      "equest\032\024.ReservationResponse\022M\n\022getReser" +
      "vationById\022\032.GetReservationByIdRequest\032\033" +
      ".GetReservationByIdResponse\022M\n\022getAllRes" +
      "ervations\022\032.GetAllReservationsRequest\032\033." +
      "GetAllReservationsResponse\022D\n\021updateRese" +
      "rvation\022\031.UpdateReservationRequest\032\024.Res" +
      "ervationResponse\022J\n\021deleteReservation\022\031." +
      "DeleteReservationRequest\032\032.DeleteReserva" +
      "tionResponseB\025\n\021org.example.stubsP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "Client", "Chambre", "DateDebut", "DateFin", "Preferences", });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
