// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package org.example.stubs;

public interface GetReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  org.example.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  org.example.stubs.ReservationOrBuilder getReservationOrBuilder();
}
