// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package org.example.stubs;

public interface UpdateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string clientId = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string chambreId = 3;</code>
   * @return The chambreId.
   */
  java.lang.String getChambreId();
  /**
   * <code>string chambreId = 3;</code>
   * @return The bytes for chambreId.
   */
  com.google.protobuf.ByteString
      getChambreIdBytes();

  /**
   * <code>string dateDebut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
